--- Credits to the original authors of [Eldritch](https://github.com/eldritch-theme/eldritch)
--- This is just a port for NvChad's theme engine: base46
---@class Base46Table
local M = {}

M.base_30 = {
  white = "#EBFAFA",
  darker_black = "#1D1E2D",
  black = "#1F2030",
  black2 = "#292A40",
  one_bg = "#30314A",
  one_bg2 = "#393a58",
  one_bg3 = "#424365",
  grey = "#636699",
  grey_fg = "#7275a4",
  grey_fg2 = "#6A6D9F",
  light_grey = "#3B4261",
  red = "#F16C75",
  baby_pink = "#F265B5",
  pink = "#BE60A0",
  line = "#383A57",
  green = "#37f499",
  vibrant_green = "#00FA82",
  nord_blue = "#0F94Ae",
  blue = "#10A1BD",
  yellow = "#F1FC79",
  sun = "#F2FC84",
  purple = "#A48CF2",
  dark_purple = "#5866A2",
  teal = "#33C57F",
  orange = "#f7C67F",
  cyan = "#04D1F9",
  statusline_bg = "#1F2030",
  lightbg = "#292E42",
  pmenu_bg = "#37F499",
  folder_bg = "#8C99A4",
  lavender = "#A48CF2",
}

M.base_16 = {
  base00 = "#1f2030",
  base01 = "#1f2030",
  base02 = "#212337",
  base03 = "#3B4261",
  base04 = "#8386A8",
  base05 = "#ABB4DA",
  base06 = "#EBFAFA",
  base07 = "#ABB2BF",
  base08 = "#F16C75",
  base09 = "#F16C75",
  base0A = "#F7C67F",
  base0B = "#F1FC79",
  base0C = "#10A1BD",
  base0D = "#7081D0",
  base0E = "#A48CF2",
  base0F = "#F16C75",
}

M.polish_hl = {
  defaults = {
    CursorLine = { bg = M.base_30.black },
    CursorLineNr = { fg = M.base_30.yellow, bold = true },
    FloatBorder = { fg = M.base_30.purple },
    LineNr = { fg = M.base_30.light_grey },
    LspInfoBorder = { fg = M.base_30.purple },
    MatchWord = { bg = M.base_30.black2, fg = M.base_30.grey },
    PmenuSel = { bg = M.base_30.purple },
    Visual = { bg = M.base_30.black2 },
  },
  treesitter = {
    Comment = { fg = M.base_30.dark_purple },
    ["@variable.member"] = { fg = M.base_30.baby_pink },
    ["@variable.parameter"] = { fg = M.base_30.purple },
    ["@punctuation.delimiter"] = { fg = M.base_30.grey },
    ["@function.builtin"] = { fg = M.base_30.cyan },
    ["@punctuation.bracket"] = { fg = M.base_30.grey },
    ["@tag.delimiter"] = { fg = M.base_30.grey },
    ["@constructor"] = { fg = M.base_30.grey },
    ["Function"] = { fg = M.base_30.baby_pink },
    ["@function"] = { fg = M.base_30.baby_pink },
    ["@function.call"] = { fg = M.base_30.baby_pink },
    ["@function.method.call"] = { fg = M.base_30.baby_pink },
    ["@function.macro"] = { fg = M.base_30.purple },
    ["@keyword"] = { fg = M.base_30.green },
    ["@keyword.import"] = { fg = M.base_30.green },
    ["@keyword.storage"] = { fg = M.base_30.green },
    ["@keyword.directive"] = { fg = M.base_30.green },
    ["@keyword.conditional"] = { fg = M.base_30.green },
    ["@keyword.function"] = { fg = M.base_30.green },
    ["@keyword.repeat"] = { fg = M.base_30.green },
    ["@keyword.return"] = { fg = M.base_30.green },
    ["@keyword.import.tsx"] = { fg = M.base_30.green },
    ["@property"] = { fg = M.base_30.purple },
    ["@operator"] = { fg = M.base_30.cyan },
    ["@constant"] = { fg = M.base_30.purple },
    ["@type.builtin"] = { fg = M.base_30.cyan },
    ["@variable"] = { fg = M.base_30.purple },
    ["Special"] = { fg = M.base_30.purple },
    ["@tag"] = { fg = M.base_30.cyan },
    ["@comment"] = { fg = M.base_30.dark_purple },
  },
}

M.type = "dark"

return M
