-- Credits to original theme https://github.com/MariaSolOs/dotfiles/blob/main/.config/nvim/colors/miss-dracula.lua
-- This is a modified version

local M = {}

M.base_30 = {
  white = "#F6F6F5",
  black = "#040e18", --  nvim bg
  darker_black = "#0d1317",
  black2 = "#18222b",
  one_bg = "#1f2c37", -- real bg of onedark
  one_bg2 = "#283947",
  one_bg3 = "#314556",
  grey = "#A9ABAC",
  grey_fg = "#b2b3b4",
  grey_fg2 = "#adafb0",
  light_grey = "#4B5263",
  red = "#E95678",
  baby_pink = "#E11299",
  pink = "#E48CC1",
  line = "#273846", -- for lines like vertsplit
  green = "#87E58E",
  vibrant_green = "#97EDA2",
  nord_blue = "#BCF4F5",
  blue = "#00DFDF",
  yellow = "#E8EDA2",
  sun = "#F6F6B6",
  purple = "#BAA0E8",
  dark_purple = "#b697e1",
  teal = "#BCF4F5",
  orange = "#FFBFA9",
  cyan = "#A7DFEF",
  statusline_bg = "#1f2c37",
  lightbg = "#4B5263",
  pmenu_bg = "#97EDA2",
  folder_bg = "#598cbf",
  lavender = "#6272A4",
}

M.base_16 = {
  base00 = "#040e18",
  base01 = "#0a0f12",
  base02 = "#0c1115",
  base03 = "#273846",
  base04 = "#A9ABAC",
  base05 = "#bfc6d4",
  base06 = "#ccd3e1",
  base07 = "#F6F6F5",
  base08 = "#E95678",
  base09 = "#FFBFA9",
  base0A = "#E8EDA2",
  base0B = "#97EDA2",
  base0C = "#A7DFEF",
  base0D = "#598cbf",
  base0E = "#BAA0E8",
  base0F = "#E95678",
}

M.polish_hl = {
  treesitter = {
    ["@annotation"] = { fg = M.base_30.yellow },
    ["@attribute"] = { fg = M.base_30.cyan },
    ["@boolean"] = { fg = M.base_30.purple },
    ["@character"] = { fg = M.base_30.green },
    ["@constant"] = { fg = M.base_30.purple },
    ["@constant.builtin"] = { fg = M.base_30.purple },
    ["@constant.macro"] = { fg = M.base_30.cyan },
    ["@constructor"] = { fg = M.base_30.cyan },
    ["@error"] = { fg = M.base_30.baby_pink },
    ["@function"] = { fg = M.base_30.green },
    ["@function.builtin"] = { fg = M.base_30.cyan },
    ["@function.macro"] = { fg = M.base_30.green },
    ["@function.method"] = { fg = M.base_30.green },
    ["@keyword"] = { fg = M.base_30.pink },
    ["@keyword.conditional"] = { fg = M.base_30.pink },
    ["@keyword.exception"] = { fg = M.base_30.purple },
    ["@keyword.function"] = { fg = M.base_30.cyan },
    ["@keyword.function.ruby"] = { fg = M.base_30.pink },
    ["@keyword.include"] = { fg = M.base_30.pink },
    ["@keyword.operator"] = { fg = M.base_30.pink },
    ["@keyword.repeat"] = { fg = M.base_30.pink },
    ["@label"] = { fg = M.base_30.cyan },
    ["@markup"] = { fg = M.base_30.orange },
    ["@markup.emphasis"] = { fg = M.base_30.yellow, italic = true },
    ["@markup.heading"] = { fg = M.base_30.pink, bold = true },
    ["@markup.link"] = { fg = M.base_30.orange, bold = true },
    ["@markup.link.uri"] = { fg = M.base_30.yellow, italic = true },
    ["@markup.list"] = { fg = M.base_30.cyan },
    ["@markup.raw"] = { fg = M.base_30.yellow },
    ["@markup.strong"] = { fg = M.base_30.orange, bold = true },
    ["@markup.underline"] = { fg = M.base_30.orange },
    ["@module"] = { fg = M.base_30.orange },
    ["@number"] = { fg = M.base_30.purple },
    ["@number.float"] = { fg = M.base_30.green },
    ["@operator"] = { fg = M.base_30.pink },
    ["@parameter.reference"] = { fg = M.base_30.orange },
    ["@property"] = { fg = M.base_30.purple },
    ["@string"] = { fg = M.base_30.yellow },
    ["@string.escape"] = { fg = M.base_30.cyan },
    ["@string.regexp"] = { fg = M.base_30.baby_pink },
    ["@string.special.symbol"] = { fg = M.base_30.purple },
    ["@structure"] = { fg = M.base_30.purple },
    ["@tag"] = { fg = M.base_30.cyan },
    ["@tag.attribute"] = { fg = M.base_30.green },
    ["@tag.delimiter"] = { fg = M.base_30.cyan },
    ["@type"] = { fg = M.base_30.nord_blue },
    ["@type.builtin"] = { fg = M.base_30.cyan, italic = true },
    ["@type.qualifier"] = { fg = M.base_30.pink },
    ["@variable.builtin"] = { fg = M.base_30.purple },
    ["@variable.member"] = { fg = M.base_30.orange },
    ["@variable.parameter"] = { fg = M.base_30.orange },
  },
}

M.type = "dark"

return M
